/*
 * File: app/store/MyStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('datos_locales.store.MyStore', {
    extend: 'Ext.data.Store',

    requires: [
        'datos_locales.model.MyModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.util.Grouper'
    ],

    config: {
        autoLoad: true,
        model: 'datos_locales.model.MyModel',
        storeId: 'MyStore',
        proxy: {
            type: 'ajax',
            url: '/datos_locales/resources/data/convertcsv.json',
            reader: {
                type: 'json',
                rootProperty: 'roads'
            }
        },
        grouper: {
            groupFn: function(item) {
                return item.get('subtitle');
            }
        }
    }
});